language: android
jdk: oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`  see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - tools
    - platform-tools

    - build-tools-25.0.0
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email:
    - gudong.name@gmail.com
